title: Zane Kelley
baseurl: ""
url: "https://zanekelley.github.io" 
description: >-
  Personal website and academic portfolio.

remote_theme: LeNPaul/academic

plugins:
  - jekyll-remote-theme

markdown: kramdown
