title: "Zane Kelley"
description: "Personal academic website"
url: "https://zanekelley.github.io"
baseurl: ""

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/blog/page:num"

navigation:
  - title: "Zane Kelley"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/

author:
  name: "Zane Kelley"
  email: "zane.kelley@nyu.edu"
  avatar: ""  # leave blank to remove homepage image
