title: "Zane Kelley"
description: "Personal academic website"
url: "https://zanekelley.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

navigation:
  - title: ""
    url: /

author:
  name: "Zane Kelley"
  email: "zane.kelley@nyu.edu"
  avatar: ""  # leave blank to remove homepage image
